### ISSUE TITLE
breaks github editor

### ISSUE THREAD

**Issue by teridon** [ubershmekel/default-scrollbar#1]
Thanks for making this extension!  I hate when sites mess with my scrollbar.

However, this extension seems to break the github file editor.  It would be nice if there was a way to exclude some sites.

**Comment by ubershmekel** [comment]
Sorry about this. I fixed it, republished on the Chrome store, and I just now noticed that there was a checkbox I didn't tick. So this may have not been live until now.

Can you go to chrome://extensions/?id=nkjmoagfbmeafonfhbkeicjdhjlofplo and see if it's version 1.2? If not, please click `Update`. Then retest?

Thank you @teridon

**Comment by teridon** [comment]
yep, the new version is available in the store now, and it appears to resolve the issue.  Thanks!
