### ISSUE TITLE
Manifest v3 for Chrome in 2023+

### ISSUE THREAD

**Issue by krystian3w** [ubershmekel/default-scrollbar#3]
If you no drop support in future (promote use Brave, Opera, Vivalidi or Edge).

> https://github.com/ubershmekel/default-scrollbar/blob/a754666cf2a1ce702e0ab8e794f897e7036372b5/manifest.json#L44

**Comment by ubershmekel** [comment]
I'm not sure I understood what you just wrote there. But I've updated to manifest v3 just now 13e42678a4015b09c14b29cd758d353c3084cb68 so thanks for the notice.

Was that what you meant?

**Comment by krystian3w** [comment]
I meant problem with install addon on June 2023 in Chrome form official webstore if other Chromium browsers don't remove API "v2" (and start use Opera Store as base or own stories).


https://github.com/dhowe/AdNauseam/issues/2084
